// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5CGyMDPjJLQETvk6SnLeqLe0Z5w5mbgo',
    appId: '1:571896163252:web:827dffc630a30f419ca0e1',
    messagingSenderId: '571896163252',
    projectId: 'fir-demo-b9149',
    authDomain: 'fir-demo-b9149.firebaseapp.com',
    storageBucket: 'fir-demo-b9149.firebasestorage.app',
    measurementId: 'G-EER3NHBVF7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCi8msU6A5GjVgO5bxV1Q267NfmR1m1GsY',
    appId: '1:571896163252:android:ae2d10f680e097859ca0e1',
    messagingSenderId: '571896163252',
    projectId: 'fir-demo-b9149',
    storageBucket: 'fir-demo-b9149.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpHPDcnEJHtMJ73n6Zk0vfIx-pmAjp0C0',
    appId: '1:571896163252:ios:59b6b11e943948879ca0e1',
    messagingSenderId: '571896163252',
    projectId: 'fir-demo-b9149',
    storageBucket: 'fir-demo-b9149.firebasestorage.app',
    iosBundleId: 'com.example.firebasedemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpHPDcnEJHtMJ73n6Zk0vfIx-pmAjp0C0',
    appId: '1:571896163252:ios:59b6b11e943948879ca0e1',
    messagingSenderId: '571896163252',
    projectId: 'fir-demo-b9149',
    storageBucket: 'fir-demo-b9149.firebasestorage.app',
    iosBundleId: 'com.example.firebasedemo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5CGyMDPjJLQETvk6SnLeqLe0Z5w5mbgo',
    appId: '1:571896163252:web:70c69c27add869d69ca0e1',
    messagingSenderId: '571896163252',
    projectId: 'fir-demo-b9149',
    authDomain: 'fir-demo-b9149.firebaseapp.com',
    storageBucket: 'fir-demo-b9149.firebasestorage.app',
    measurementId: 'G-JS0DG1QF22',
  );
}
